### ISSUE TITLE
RFC 0019: Allow RAILS_ENV to be overridden at build time

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/rails-assets#200]
Paketo [RFC 0019](https://github.com/paketo-buildpacks/rfcs/blob/2ad006cd21cb3fa97026ce28328f587c6dded664/text/0019-buildpack-set-env-vars-defaults.md) states that users should be able to override environment variables that the buildpacks set, if they're environment variables commonly used in the language ecosystem.

In this buildpack, the assets precompile step [sets `RAILS_ENV`](https://github.com/paketo-buildpacks/rails-assets/blob/00cd7ea1bdc6af11d15ce0ce7ce7e73d9d176b2e/precompile_process.go#L38) in a way that ignores any user-provided value for the environment variable. This locks users into configuration that may not work for their app.  For instance, to build https://github.com/pglombardo/PasswordPusher without an external DB, [`RAILS_ENV` must be set to `private`](https://github.com/pglombardo/PasswordPusher/blob/8bbee221cf4e591bd03300b683957ad7d15c2131/containers/docker/pwpush-ephemeral/Dockerfile#L27). 

If it's possible for the buildpack to function while respecting that environment variable, it should do so.

**Comment by thedarkside** [comment]
I ran into an issue today which is worth mentioning here as well. 

After i build a new rails project i observed a difference in behavior to my previous rails projects build with the exact same buildpack. After digging around ive seen the RAILS_ENV wasnt set while in my previous projects it was set!

After spending some time comparing those projects i stumbled upon the line in this project which sets the RAILS_ENV. 
Well, my new rails project is an api project and thus has no asset pipeline included. Ive expected the RAILS_ENV variable to be set because it has a dependency to **rails** and not **rails-assets** in particular.

Maybe its a good idea to extract rails-only dependent stuff into its on "rails" project?

**Comment by robdimsdale** [comment]
@thedarkside that's a good point. I think there's value in exploring this. I opened [this issue](https://github.com/paketo-buildpacks/ruby/issues/982) to support Rails API applications that do not have assets.
